// Mirrors server/constants/auditActions.js for the filter dropdown.
export const AUDIT_ACTIONS = [
  'ADMIN_LOGIN',
  'ADMIN_LOGIN_FAILED',
  'ADMIN_LOGOUT',
  'USER_INFORMATION_UPDATED',
  'APPLICATION_STATUS_UPDATED',
  'APPLICATION_INFORMATION_UPDATED',
  'INTERNAL_NOTE_ADDED',
  'DOCUMENT_VERIFIED',
  'DOCUMENT_REUPLOAD_REQUESTED',
  'INFORMATION_REQUEST_CREATED',
  'OTP_REQUESTED',
  'SCHEME_CREATED',
  'SCHEME_UPDATED',
  'SCHEME_ACTIVATED',
  'SCHEME_DEACTIVATED',
  'PRICE_UPDATED',
  'NOTIFICATION_SENT',
  'REFUND_REQUESTED',
  'REFUND_APPROVED',
  'REFUND_REJECTED',
  'ADMIN_CREATED',
  'ADMIN_REMOVED',
];

export const ENTITY_TYPES = ['user', 'application', 'scheme', 'document', 'admin', 'notification'];
