// Central registry of audit action names. Using a constant instead of raw
// strings prevents typos from silently creating untracked action types.
const AUDIT_ACTIONS = Object.freeze({
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  ADMIN_LOGIN_FAILED: 'ADMIN_LOGIN_FAILED',
  ADMIN_LOGOUT: 'ADMIN_LOGOUT',

  USER_INFORMATION_UPDATED: 'USER_INFORMATION_UPDATED',
  APPLICATION_STATUS_UPDATED: 'APPLICATION_STATUS_UPDATED',
  APPLICATION_INFORMATION_UPDATED: 'APPLICATION_INFORMATION_UPDATED',
  INTERNAL_NOTE_ADDED: 'INTERNAL_NOTE_ADDED',

  DOCUMENT_VERIFIED: 'DOCUMENT_VERIFIED',
  DOCUMENT_REUPLOAD_REQUESTED: 'DOCUMENT_REUPLOAD_REQUESTED',

  INFORMATION_REQUEST_CREATED: 'INFORMATION_REQUEST_CREATED',

  OTP_REQUESTED: 'OTP_REQUESTED',

  SCHEME_CREATED: 'SCHEME_CREATED',
  SCHEME_UPDATED: 'SCHEME_UPDATED',
  SCHEME_ACTIVATED: 'SCHEME_ACTIVATED',
  SCHEME_DEACTIVATED: 'SCHEME_DEACTIVATED',
  PRICE_UPDATED: 'PRICE_UPDATED',

  NOTIFICATION_SENT: 'NOTIFICATION_SENT',

  REFUND_REQUESTED: 'REFUND_REQUESTED',
  REFUND_APPROVED: 'REFUND_APPROVED',
  REFUND_REJECTED: 'REFUND_REJECTED',

  ADMIN_CREATED: 'ADMIN_CREATED',
  ADMIN_REMOVED: 'ADMIN_REMOVED',
});

module.exports = { AUDIT_ACTIONS };
